Resources:
  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: database123
      DBName:  sfl_db
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro
      Engine: "postgres"
      EngineVersion: "12.5"
      MasterUsername: "my_dev"
      MasterUserPassword: "samsideen_dev"
      PubliclyAccessible: false
      DBSubnetGroupName: rds-postgres-dbsubnetgroup-bhekywkvgemk
      StorageType: gp2
      VPCSecurityGroups:
        - sg-0ef293378a0422ee8
      MultiAZ: false
    DeletionPolicy: "Snapshot"
 