Resources:
  Mys3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private 
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: sfl-s3 
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
      #Tags: 
       # - Key: Owner
        #  Value !Ref Owner
